# Generated by Django 4.2.1 on 2023-05-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=50, verbose_name='Type'),
        ),
    ]
