# Generated by Django 4.2.1 on 2023-05-19 05:33

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('budget', models.IntegerField(default=0, verbose_name='Budget')),
                ('profile', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Profile Image')),
                ('token', models.CharField(max_length=500, verbose_name='Token')),
                ('token_expires', models.DateTimeField(verbose_name='Token Expires')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_At')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
